### PR TITLE
Disable hosts entry remove when port-forward fails on one of the service ports

### PR DESCRIPTION
**Pull request by flupec**
There are exactly one line in hosts file corresponding to particular kubernetes service, however, kubernetes service can have a different ports and different ports can be accessible or not. If there are any issue with one of the ports then kubefwd will remove corresponding line from hosts file, which is unwanted behavior.

### CODE REVIEW

**Comment by fgblomqvist** [comment]
I have hit this as well and it ends up being a tricky problem to debug since I might want to access `foo:8000`, which kubefwd says is working fine, but in reality the hostname is gone because it failed to forward `foo:8001`. Thanks for making this PR, hopefully it'll get merged sooner rather than later!

**Comment by flupec** [comment]
Sorry, this PR is buggy for now. I'm working on it

**Comment by cjimti** [comment]
thanks @flupec. The current release of `kubefwd` is stable for my use case and due to my lack of a decent test suite it takes me a long time to test PRs. If you are interested in contributing test code I would really appreciate it!

**Comment by flupec** [comment]
Now you can review this code

**Comment by cjimti** [comment]
@flupec I have not had time to figure out why but this does sometimes leave entries in `/etc/hosts` after I exit. Can you look into that. Otherwise it seems to work good.

**Comment by flupec** [comment]
@cjimti Sorry i cannot reproduce this neither on Windows and Linux Mint. I used to have a problems with entries in `/etc/hosts` in previous releases, now i think problem is gone. Can you share more information about your case?

**Comment by cjimti** [comment]
@flupec It does not clean up services that failed to forward to a Pod. This does not happen with release 1.20.0.

I have steps to re-produce.

- Create a service that listens on a port like `8888` and properly forwards to a pod. 
- Listen to that service on all local interfaces (`nc -l 8888`) on your local workstation
- run `kubefwd`

`kubefwd` can't bind  `8888` locally since it's already bound to all interfaces and will produce the following error: 

```
ERRO[10:20:50] ForwardPorts error: unable to listen on any of the requested ports: [{8888 8888}]
```

- stop `kubefwd` and any services that use  `8888` will still be present in the `/etc/hosts`

**Comment by cjimti** [comment]
@flupec let me know if you plan to fix this. Otherwise I'll need to revert it before I can make a new version. Thanks!

**Comment by flupec** [comment]
I plan to fix this as soon as I can reproduce it on v1.20.0. So far, I have not been able to do this, it may be that the servers are very far away.

By the way, please note that this case is covered by the test https://github.com/txn2/kubefwd/pull/189/files#diff-8c542812b34bd04887cdb7a98af150ab46e4a06c02f591e76e9a70dad702ba0cR18

**Comment by flupec** [comment]
@cjimti Can anyone else confirm this behavior?

**Comment by cjimti** [comment]
@flupec This does not happen in `1.20.0` and I can reproduce it consistently on `master` with this PR. 

I have a namespace with two postgres services listening on `5432`. If I run `nc -l 5432` before I run `kubefwd` I am binding `5432` on all interfaces and `kubfwd` fails to bind **as expected**:

```
ERRO[00:21:58] ForwardPorts error: unable to listen on any of the requested ports: [{5432 5432}] 
ERRO[00:22:05] ForwardPorts error: unable to listen on any of the requested ports: [{5432 5432}] 
```

When I exit clean on `v1.20.0` I get a clean `/etc/hosts`:

```
$ cat /etc/hosts
127.0.0.1        localhost
127.0.1.1        straylight-desk

# The following lines are desirable for IPv6 capable hosts
::1              ip6-localhost ip6-loopback
fe00::0          ip6-localnet
ff00::0          ip6-mcastprefix
ff02::1          ip6-allnodes
ff02::2          ip6-allrouters
```

When I exit after running on the `master` branch I get:
```
127.0.0.1        localhost
127.0.1.1        straylight-desk

# The following lines are desirable for IPv6 capable hosts
::1              ip6-localhost ip6-loopback
fe00::0          ip6-localnet
ff00::0          ip6-mcastprefix
ff02::1          ip6-allnodes
ff02::2          ip6-allrouters
127.1.27.4       opsdb-cluster-repl opsdb-cluster-repl.pmgsc opsdb-cluster-repl.pmgsc.svc opsdb-cluster-repl.pmgsc.svc.cluster.local opsdb-cluster-repl.pmgsc.gpu1 opsdb-cluster-repl.pmgsc.svc.gpu1 opsdb-cluster-repl.pmgsc.svc.cluster.gpu1
127.1.27.20      whdb-cluster-repl whdb-cluster-repl.pmgsc whdb-cluster-repl.pmgsc.svc whdb-cluster-repl.pmgsc.svc.cluster.local whdb-cluster-repl.pmgsc.gpu1 whdb-cluster-repl.pmgsc.svc.gpu1 whdb-cluster-repl.pmgsc.svc.cluster.gpu1
```

The `127.1.27.4` and `127.1.27.20` are mapped to the pods that could not bind to `5432` as expected. However the `/etc/hosts` entries remain. 

I have not had time to look at it deeper but it seems the code you added is not accounting for hosts that were never able to bind to any port. This happens often for people running web servers on their local workstation binding `80` or `8080` to `0.0.0.0`. 

I just don't want `kubefwd` to leave an unnecessary mess in the `/etc/hosts`.

**Comment by flupec** [comment]
Yes, it looks like there are problems in the master branch. Sorry, it was misunderstanting between us.
My P/R included in v1.20.0 and it works fine.


If you execute `git diff master..v1.20.0` then we can see that there are differences only in `go.sum` file.
I'm pretty sure my code is working correctly. But I can try to figure out why the master branch behaves in a completely different way.


Hopefully, i can take a look into it at a weekend.

**Comment by cjimti** [comment]
@flupec thanks for helping me look into it.

**Pull request merged**
