### PR TITLE
Move saving of hosts file to after all ports are forwarded

### LINKED ISSUE #74: Race when updating hosts file?
I am observing a peculiar issue when running kubefwd with multiple services.

Im an running on Windows with Docker Desktop.

Docker Desktop adds the following entry in the hosts file during installation "127.0.0.1 kubernetes.docker.internal" and it is this host that is specified in the cluster section in the `.kube\config` file (seen by `kubectl config view`). The result is that the port-forwarding commands are sent to `https://kubernetes.docker.internal:6443/...`.

However, if kubefwd forwards multiple services, it happens at random that the following error is returned when forwarding services:
```
ERROR: error upgrading connection: error sending request: Post https://kubernetes.docker.internal:6443/api/v1/namespaces/default/pods/mypod-6dd464d68b-mhk29/portforward?timeout=32s: dial tcp: lookup kubernetes.docker.internal: no such host
```

Whether the error is shown for a pod or not seems random, however if a selector is specified so that only one service is selected, then the error never shows.

If I update the `.kube\config` file to have `server: https://localhost:6443` then forwarding starts correctly everytime.

I have tried removing the call to [pfo.Hostfile.Save()](https://github.com/txn2/kubefwd/blob/master/pkg/fwdport/fwdport.go#L116) and it seems to solve the problem.

### PR DESCRIPTION
**Pull request by rmja**
This fixes #74

### CODE REVIEW

**Comment by cjimti** [comment]
@rmja Thank you for working on this. I can take a deeper look at it this coming weekend. I have some things to contemplate. Some people would like `kubefwd` to monitor connections and re-connect on pod failures, which would mean removing and adding new entries through the duration of the run. In other circumstances, some people on my team do not want to wait till all forwards have completed before they can start accessing services that have begun their forward (we have some namespaces with  hundreds of services.) There is another ticket asking for a feature to monitor a namespace and forward any new services. These conditions all make the case for keeping isolated writes to `/etc/hosts`. I am hoping that I can think of a workable compromise.

**Comment by rmja** [comment]
Year, I can see the conflict. How about assigning IP's and writing the hosts file up front, and then actually map the services afterwards?

**Comment by cjimti** [comment]
@rmja I am going to merge this and test a few adjustments. I need to work on #75 which is somewhat related in that kubefwd does not reload the state of `/etc/hosts` before removing entries and saving, therefore saving over any entries added by other processes while `kubefwd` is sunning.

**Comment by cjimti** [comment]
In relase [1.9.1](https://github.com/txn2/kubefwd/releases/tag/v1.9.1)

I split the difference. The initial write to `/etc/hosts/' happens after all the forwards have completed (per your PR) however I need to reload and save when exiting each routine to fix #75.

Thank you for your contribution!

**Pull request merged**
