### PR TITLE
Update to go 1.16, allowing darwin/arm64 releases

### PR DESCRIPTION
**Pull request by n-oden**
Presently installing kubefwd on darwin/arm64 (macos/apple silicon) requires installing the x86_64 version of homebrew or installing from source.  Go 1.16 has first class support for GOOS=darwin / GOARCH=arm64.

- update go.mod, go.sum
- update travis config
- update goreleaser config
- fix one go vet error

### CODE REVIEW

**Review by x — APPROVED** [review]
Looks sane. I approve of this in spirit. However, it should definitely have rf's sign-off :)

**Comment by cjimti** [comment]
LGTM I can take a better look tomorrow, merge and cut a release. Thanks!

**Comment by cjimti** [comment]
I released version 1.19.0. I don't have any apple silicon to test this with. 

https://github.com/txn2/kubefwd/releases/tag/1.19.0

**Comment by n-oden** [comment]
Awesome!  I can confirm that it's working on my Apple Silicon devices:

```
INFO[13:58:18]  _          _           __             _
INFO[13:58:18] | | ___   _| |__   ___ / _|_      ____| |
INFO[13:58:18] | |/ / | | | '_ \ / _ \ |_\ \ /\ / / _  |
INFO[13:58:18] |   <| |_| | |_) |  __/  _|\ V  V / (_| |
INFO[13:58:18] |_|\_\\__,_|_.__/ \___|_|   \_/\_/ \__,_|
INFO[13:58:18]
INFO[13:58:18] Version 1.19.0
INFO[13:58:18] https://github.com/txn2/kubefwd
```

**Pull request merged**
