### PR TITLE
On service change

### PR DESCRIPTION
**Pull request by robblovell**
This is an attempt to restart Kubefwd when pods it is forwarding to are modified or deleted.

### CODE REVIEW

**Comment by robblovell** [comment]
On rebasing to the current master, this solution no longer works. Uncommenting the call to ListenUntilPodDeleted now breaks everything.  

It does look like the current master branch is moving toward fixing the problem of having the forwarded pod deleted out from under the forward. I am going to study this a bit longer, but if a solution is on the way, please let me know and I will withdraw this work.

**Comment by cjimti** [comment]
@robblovell thank you for a desire to contribute to this project. I need to put this on hold for a bit. Please see my comment on https://github.com/txn2/kubefwd/issues/169#issuecomment-875936713

**Comment by robblovell** [comment]
thanks @cjimti for the feedback, I have made some more changes and will look for the instability. It appears that it works, but the restart can leave previous connections broken in a way that requires restarts of clients.  When this error occurs:
```
ERRO[18:27:40] Runtime: error creating error stream for port 3000 -> 80: Timeout occurred 
```
Then there's a client out there somewhere that is still trying to connect on the shutdown connection. 

I will continue to look at this on our fork and let you know if I find a way to stabilize this.

**Comment by robblovell** [comment]
I have a version that is stable from what I can tell. Even if the "error creating error stream for port..." error occurs, connected clients recover. I haven't tested this with a large number of pods or high traffic, but I have restarted pods over and over with no hung connection failures. Clients eventually recover. Of course, you can still restart kubefwd to recover faster.

Let me know if or when you would like to review the new work. (https://github.com/c6o/kubefwd/pull/1).

**Pull request closed without merging**
