### PR TITLE
Feature/add all ns

### PR DESCRIPTION
**Pull request by ndj888**
#204

### CODE REVIEW

**Comment by cjimti** [comment]
@ndj888 the new argument give me an error message:

`sudo go run ./cmd/kubefwd/kubefwd.go svc -A` or `sudo go run ./cmd/kubefwd/kubefwd.go svc --all-namespaces`

Result:
```
FATA[20:56:08] Error --all-namespace not use -n.            
exit status 1
```

**Review by ndj888 — COMMENTED** [review]
The namespace variable had default value , so the len(namespace) >= 1 not working. 
Change it , len(namespace) > 1 ,it working.

**Comment by cjimti** [comment]
@ndj888 good fix however it now allows the following:

`sudo go run ./cmd/kubefwd/kubefwd.go svc -n default --all-namespaces`

No error is given, I assume you want to error here.

Also I believe the error `Error --all-namespace not use -n.` would be better expressed as:

`Error: cannot combine options --all-namespaces and -n.'

**Review by ndj888 — COMMENTED** [review]
@cjimti "Error: cannot combine options --all-namespaces and -n." This may be more accurate in expression

**Pull request merged**
